volumes:
  loki_data: {}
  promtail_positions: {}

services:
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    restart: unless-stopped
    ports:
      - "${LOKI_PORT}:3100"
    volumes:
      - loki_data:/loki
      - ./loki/loki-config.yml:/etc/loki/local-config.yml:ro
    command:
      - --config.file=/etc/loki/local-config.yml

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    restart: unless-stopped
    depends_on:
      - loki
    volumes:
      - /var/log:/var/log:ro
      - promtail_positions:/positions
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml:ro
    command:
      - --config.file=/etc/promtail/config.yml
